### ISSUE TITLE
More parsing options ?

### ISSUE THREAD

**Issue by EmmanuelBeziat** [binocarlos/markdown-parse#1]
Hi!

I really appreciate your parser, it’s fairly simple to use and ready-to-go. But the point is, i need some extra markdown capacities for the content (like https://github.com/arve0/markdown-it-attrs). How could I achieve this ?

Because once inside the parsing function, `result.html` is already parsed and thus can’t be re-parsed through another script.

``` javascript
markdown(post, function(err, result) {
    fileContent.posts.push({
        'title': result.attributes.title,
        'date': result.attributes.date || new Date(),
        'tags': result.attributes.tags || [''],es.title, { lower: true }),
        'content': result.html // doing anything at this is pointless, as it’s already parsed
    })
})
```

Thanks!

**Comment by binocarlos** [comment]
Hey - thanks for the feedback,

Could you use the `body` property - which is the original unparsed markdown body (minus frontmatter).

``` javascript
var md = require('markdown-it')();
var markdownItAttrs = require('markdown-it-attrs');
var parser = require('markdown-parse');
md.use(markdownItAttrs);
parser(post, function(err, result) {
    fileContent.posts.push({
        'title': result.attributes.title,
        'date': result.attributes.date || new Date(),
        'tags': result.attributes.tags || { lower: true },
        'content': md.render(result.body)
    })
})

```

Is that what you mean?

**Comment by EmmanuelBeziat** [comment]
My bad, I totally forgot about the unparsed "body". This is perfect!
